create table [SCOLARITE_FACT](
	id int identity(1,1) primary key,
	ANNEE_ID int FOREIGN KEY REFERENCES [ANNEE_DIM](id),
	ANNEE_VALIDATION_ID int FOREIGN KEY REFERENCES [ANNEE_VALIDATION_DIM](id),
	ETUDIANT_ID int FOREIGN KEY REFERENCES ETUDIANT_DIM(id),
	FILIERE_ID int FOREIGN KEY REFERENCES FILIERE_DIM(id),
	MODULE_ID int FOREIGN KEY REFERENCES MODULE_DIM(id),
	RESULTAT_ID int FOREIGN KEY REFERENCES RESULTAT_DIM(id),
	SEMESTRE_ID int FOREIGN KEY REFERENCES SEMESTRE_DIM(id),
	SESSION_ID int FOREIGN KEY REFERENCES SESSION_DIM(id),
	SEXE_ID int FOREIGN KEY REFERENCES SEXE_DIM(id),
	BAC_ID int FOREIGN KEY REFERENCES BAC_DIM(id),
	VILLE_ID int FOREIGN KEY REFERENCES VILLE_DIM(id),
	NOTE real
);

insert into [SCOLARITE_FACT](ANNEE_ID, ANNEE_VALIDATION_ID, ETUDIANT_ID, FILIERE_ID, MODULE_ID, RESULTAT_ID, SEMESTRE_ID, SESSION_ID, SEXE_ID, BAC_ID, VILLE_ID, NOTE) select 
[ANNEE_DIM].id AS "ANNEE_ID",
[ANNEE_VALIDATION_DIM].id AS "ANNEE_VALIDATION_ID",
ETUDIANT_DIM.id AS "ETUDIANT_ID",
FILIERE_DIM.id AS "FILIERE_ID",
MODULE_DIM.id AS "MODULE_ID",
RESULTAT_DIM.id AS "RESULTAT_ID",
SEMESTRE_DIM.id AS "SEMESTRE_ID",
SESSION_DIM.id AS "SESSION_ID",
SEXE_DIM.id AS "SEXE_ID",
BAC_DIM.id AS "BAC_ID",
VILLE_DIM.id AS "VILLE_ID",
NOTE
FROM [STAGE] 
LEFT JOIN [ANNEE_DIM] ON [STAGE].ANNEE = [ANNEE_DIM].[ANNEE]
LEFT JOIN [ANNEE_VALIDATION_DIM] ON [STAGE].[ANNEE VALIDATION] = [ANNEE_VALIDATION_DIM].[ANNEE_VALIDATION]
LEFT JOIN ETUDIANT_DIM ON [STAGE].COD_ETU = ETUDIANT_DIM.COD_ETU
LEFT JOIN FILIERE_DIM ON [STAGE].FILIERE = FILIERE_DIM.FILIERE
LEFT JOIN MODULE_DIM ON [STAGE].MODULE = MODULE_DIM.MODULE
LEFT JOIN RESULTAT_DIM ON [STAGE].RESULTAT = RESULTAT_DIM.RESULTAT
LEFT JOIN SEMESTRE_DIM ON [STAGE].SEMESTRE = SEMESTRE_DIM.SEMESTRE
LEFT JOIN SESSION_DIM ON [STAGE].[SESSION] = SESSION_DIM.[SESSION]
LEFT JOIN SEXE_DIM ON [STAGE].SEXE = SEXE_DIM.SEXE
LEFT JOIN BAC_DIM ON [STAGE].BAC = BAC_DIM.[TYPE BAC]
LEFT JOIN VILLE_DIM ON [STAGE].VILLE = VILLE_DIM.VILLE;